### ISSUE TITLE
Tutoiement

### ISSUE THREAD

**Issue by bl4ckout31** [THEDARKK/Guide#1]
Tous les « **De quoi as-tu besoin** » devrait être « **De quoi avez-vous besoin** »  pour rester cohérent avec le reste du texte qui est en vouvoiement.

**Comment by coc4tm** [comment]
Oui , il faut tout faire en tutoiement ou en vouvoiment

**Comment by THEDARKK** [comment]
Salut , je vous mette les droits pour modifié 👍

**Comment by bl4ckout31** [comment]
Finalement, je pense que « **De quoi ai-je besoin ?** » ou « **Ce dont vous avez besoin** » serait plus approprié.

**Comment by coc4tm** [comment]
Oui , je confirme . @THEDARKK t'es ok ?

**Comment by THEDARKK** [comment]
@bl4ckout31 @coc4tm OK

**Comment by coc4tm** [comment]
J'ai réglé le probleme
